name: Release Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
    - name: Check Repo
      uses: actions/Checkout@v2

    - name: Build Backend Docker Image
      run: | 
        cd react-express-mongodb/backend
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest .

    - name: Pushhh Backend Docker Image
      run: |
        cd react-express-mongodb/backend
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
        
    - name: Build Frontend Docker Image 
      run: |
        cd react-express-mongodb/frontend
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest     

    - name: Pushh Frontend Docker Image
      run: |
        cd react-express-mongodb/frontend
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest


    
